CREATE DATABASE ecommerce;
USE ecommerce;

CREATE TABLE IF NOT EXISTS products (
productId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
price FLOAT NOT NULL,
productImage VARCHAR(255) NOT NULL
);

CREATE TABLE  IF NOT EXISTS orders (
orderId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
productId INT NOT NULL,
quantity INT NOT NULL,
FOREIGN KEY (productId) REFERENCES products (productId)
);

CREATE TABLE  IF NOT EXISTS users (
userId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(100),
password VARCHAR(500)
);

CREATE TABLE  IF NOT EXISTS productImages (
imageId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
productId INT NOT NULL,
path VARCHAR(255),
FOREIGN KEY (productId) REFERENCES products (productId)
);

CREATE TABLE IF NOT EXISTS categories (
categoryId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL
);